### ISSUE TITLE
[BUG] plugin doesn't start up

### ISSUE THREAD

**Issue by Onako2** [slimeixd1/tree-capitator#1]
```
[21:54:18] [Paper Plugin Remapper Thread - 1/INFO]: [PluginRemapper] Done remapping plugin 'plugins/TreeCapitator.jar' in 497ms.
[21:54:18] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Restricted name, cannot use 0x20 (space character) in a plugin name.
org.bukkit.plugin.InvalidDescriptionException: Restricted name, cannot use 0x20 (space character) in a plugin name.
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:45) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:28) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:72) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:96) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at net.minecraft.server.Main.main(Main.java:129) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at org.bukkit.craftbukkit.Main.main(Main.java:295) ~[purpur-1.21.1.jar:1.21.1-2326-4f2fe31]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Current Purpur Version: 1.21.1-2326-4f2fe31 (MC: 1.21.1)*  
* You are 1 version(s) behind  
Download the new version at: https://purpurmc.org/downloads  
Previous: 1.21.1-2308-8332fa4 (MC: 1.21.1)

Also, maybe you should upload the .java files not the .class files 🤣 .class files are the compiled files and aren't the source code

**Comment by K4R70N** [comment]
Open your .jar file with winrar or 7zip, then edit plugin.yml (open with notepad). Then edit first line and replace "Tree Capitator" with "Tree_Capitator"

**Comment by slimeixd1** [comment]
Soon, the update will go to tge Modrinth page!

(And thanks)
